export const actionTypes = {
  SIGN_IN_GOOGLE: "SIGN_IN_GOOGLE",
  SIGN_IN_EMAIL_AND_PASS: "SIGN_IN_EMAIL_AND_PASS",
  SIGN_IN_SUCCESS: "SIGN_IN_GOOGLE_SUCCESS",
  SIGN_IN_ERROR: "SIGN_IN_GOOGLE_ERROR",
  SIGN_UP_ERROR: "SIGN_UP_GOOGLE_ERROR",
  SIGN_UP_SUCCESS: "SIGN_UP_GOOGLE_SUCCESS",
  SIGN_UP_EMAIL_AND_PASS: "SIGN_UP_EMAIL_AND_PASS",
  SEND_PASS_RESET_EMAIL: "SEND_PASS_RESET_EMAIL",
  SIGN_OUT: "SIGN_OUT",
};
