export const actionTypes = {
  FETCH_PRODUCTS: "FETCH_PRODUCTS",
  ADD_PRODUCT_SHOPPING_CART:"ADD_PRODUCT_SHOPPING_CART",
  GET_LOCAL_STORAGE: "GET_LOCAL_STORAGE",
  CHANGE: "CHANGE",
  REMOVE: "REMOVE",
  ORDER_COMPLETED: "ORDER_COMPLETED",
  RESET_ORDER: "RESET_ORDER"
};
